(TeX-add-style-hook
 "chapter2"
 (lambda ()
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (LaTeX-add-labels
    "fig:minion"
    "fig:TomJerry"
    "fig:WallE"
    "fig:Minnion"
    "fig:animations"
    "sec:defGeneral"
    "sec:defLattices"
    "sec:latice-pre"
    "ssub:The motivations"
    "ssub:The mathematics"
    "fig:2dimLattice"
    "fig:paralellopiped"
    "lem:parallelopiped"
    "lem:detBasis"
    "def:determinant"
    "lem:determinant2"
    "def:minLattice"
    "the:minkowski1"
    "def:gammaSVP"
    "sub:q-ary lattices and SIS problem"
    "def:Ajtai's Hash Function"
    "the:ajtai hash"
    "def:GSO"
    "fig:gso"
    "fig:GSOAlgebra"
    "def:LLL"
    "alg:LLL"
    "theo:LLLRunTime"
    "theo:LLLShortVector"
    "theo:LLLHF"
    "rem:dimension"
    "fig:BKZParams"
    "fig:bestAttack"
    "theo:AjtaiHardness"
    "sub:LWE"
    "def:Search-LWEProb"
    "def:Decision-LWEProb"
    "theo:RegevLWEHardness"
    "def:IND-CPA Security"
    "theo:reductionCPADLWE"
    "def:PublicKeyIndCPARegev"
    "def:statisticalDistance"
    "lem:statisticalDistance"
    "lem:LHL"
    "theo:IndCPARegev"
    "def:AjtaiRing"
    "lem:SSRing-LWE"
    "sec:defHomo"
    "sec:BVScheme"
    "sub:ciphertext_packing"
    "theo:HDComputation"
    "sec:defZKP"
    "sec:zkpisis"
    "append:Stern"
    "sec:defMPP"
    "sec:syntaxModel"
    "sec:privacyReqs"))
 :latex)

